### ISSUE TITLE
Compatible with yggdrasil v0.5.x

### ISSUE THREAD

**Issue by AlexFreeman13** [one-d-wide/yggdrasil-jumper#1]
Please add compatible with yggdrasil v0.5.x

**Comment by one-d-wide** [comment]
Thank you for the first issue in this repo!

Yggdrasil-jumper 0.2.0 is now released including the support for Yggdrasil 0.5 🎉

Note that `yggdrasil-go` prior to `0.5.3` contained a [bug] that made router skip shortest path computation after a new peer has been connected. It is patched now so be sure to update.

[bug]: https://github.com/Arceliar/ironwood/commit/ad38416a77c83fd32b66d1b760d2b78ee8f09d06
